import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className=" bg-dark_bg max-w-[100vw] overflow-x-hidden text-default_color tracking-tight"
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
